### ISSUE TITLE
.addEventListener

### ISSUE THREAD

**Issue by Raynos** [Raynos/DOM-shim#10]
make it work

**Comment by Yaffle** [comment]
https://gist.github.com/1147301

**Comment by Raynos** [comment]
Thank you for the example, I'll be able to draw motivation from it.

**Comment by Yaffle** [comment]
although, there are many good things, that not fixed by this shim:
for example, "submit" and "change" events bubbling, jquery uses some tricks to fix it, so u can make it too

**Comment by Raynos** [comment]
Those kind of things will come later. DOM4 only specificies a small subset of the event specification. EventTarget is going to start off as a small shim.
