### ISSUE TITLE
Not an actual issue, just want to know how you made addEventListener work

### ISSUE THREAD

**Issue by Integralist** [Raynos/DOM-shim#30]
Hi,

As per title, this isn't a bug report.

I'm literally just interested as to how you manage to make addEventListener work on IE8 and lower?

I'd love to find out more about this technique and also how it's obviously helped you to implement the rest of the DOM shims mentioned.

Thanks!

Kind regards,
Mark

**Comment by Raynos** [comment]
When you say IE8 and lower you mean IE8. The DOM shim doesn't work in IE6/7. 

And see Interfaces/EventTarget for a buggy implementation. As noted by a few open issues I need to fix that code.

**Comment by Integralist** [comment]
Oh, ok

So this is working in IE8 and higher because you have access to its core HTML Interfaces (e.g. HTMLBodyElement etc)?

I notice http://flowjs.com/ have (apparently) got addEventListener working in IE6+ http://flowjs.com/docs/core/Event.php so I'm not sure what they're doing that works around the DOM?

**Comment by Raynos** [comment]
Yes, IE8 exposes Element.prototype, so I just bolt the method onto it.

**Comment by Raynos** [comment]
The only way I know of to make addEventListener work in IE6/7 is a htc file. That or flow does some kind of dirty hack. 

If you find a way to support IE6/7 feel free to submit a patch. Personally I don't care. And I'll drop IE8 support when IE10 hits.

**Comment by Yaffle** [comment]
note: using Element.prototype in IE8 breaks some htc...

**Comment by Raynos** [comment]
Be more specific.

What exactly in htc breaks?

Not that I care. htc's are non standard extensions. You wouldn't use the DOM shim and a htc on the same project.

**Comment by Yaffle** [comment]
css3pie.com, for example, uses htc...

**Comment by Raynos** [comment]
@Yaffle not that kind of specific. 

I mean how does extending Element.prototype break htc files?

**Comment by Yaffle** [comment]
@Raynos, i don't know, ask IE developers team

**Comment by Raynos** [comment]
@Yaffle then why make the claim

> using Element.prototype in IE8 breaks some htc

If you don't know, why, how or when it happens

**Comment by Yaffle** [comment]
1. Element.protototype.add = function something() {};
2. in htc file use "element" variable (may be other properties/getters/setter)
3. css:  \* { behavior: url("xxx.htc"); }

i can't give your full example now...

**Comment by Raynos** [comment]
I've rewritten the EventTarget module to use my own event system

https://github.com/Raynos/DOM-shim/blob/6b96c5de86935657f0ea3f18de1fbdd7fea69f88/src/ie8/interfaces/EventTarget.js

**Comment by Yaffle** [comment]
Good, but one question: error thrown by one of listeners shouldn't prevent other listeners from execution, is this problem solved in your "event system"?
example:
x.addEventListener('someevent', function () {
  throw new Error();
});
x.addEventListener('someevent', function () {
  alert(123);
});

**Comment by Raynos** [comment]
Thanks for reminding me about errors. That is not handled.

I presume the solution is try & catch. Then use a setTimeout in the catch block to continue the event system and throw the error.
