### ISSUE TITLE
Element.prototype.classList

### ISSUE THREAD

**Issue by Raynos** [Raynos/DOM-shim#6]
make it

**Comment by Yaffle** [comment]
https://gist.github.com/1306910

**Comment by Raynos** [comment]
Again thank you for the example, I'll be able to draw motivation from it.

It's not quite there yet in terms of just using it because I want to shim TokenList aswell

**Comment by Yaffle** [comment]
It will be good, if u implement TokenList,
cause i really don't know how to do it =)

**Comment by Raynos** [comment]
You cant really. Its a host object so you cant use it, what you can do is rip it out of global scope and replace it with a fake TokenList object o/
